name: Build and Deploy

on:
  push:
    branches:
      - no

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'  # 指定你需要的 Node.js 版本

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      working-directory: examples/Bootstrap-Source-code-learning
      run: npm run release

    - name: List build directory for debugging
      run: ls -al examples/Bootstrap-Source-code-learning/_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: my-public # default: gh-pages
        publish_dir: examples/Bootstrap-Source-code-learning/_site  # Change
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
